---
- hosts: terra03vm

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Ensure terrabsd has password set
      become: yes
      user:
        name: terrabsd
        password: "{{ lookup('password', './tmp/passwordfile length=63 encrypt=md5_crypt') }}"

  tasks:
    - name: Check and register if pkgng is installed (pkg -N)
      command: pkg -N
      register: pkg_bootstrap_check
      failed_when: false
      changed_when: false

    - name: Ensure pkg is bootstrapped (if not installed, based on result of the previous task)
      become: yes
      command: pkg bootstrap
      environment:
        ASSUME_ALWAYS_YES: YES
      when: "'pkg: pkg is not installed' in pkg_bootstrap_check.stderr"

    - name: Ensure pkg is updated
      become: yes
      command: pkg update
      environment:
        ASSUME_ALWAYS_YES: YES
      changed_when: false

    - name: Ensure OpenVPN is installed
      become: yes
      pkgng:
        name: openvpn
        state: present

    - name: Ensure directory for OpenVPN keys exists
      become: yes
      file:
        dest: "{{ openvpn_keys_directory }}"
        state: directory
        owner: nobody
        group: wheel
        mode: 0700

    - name: Ensure DH is present
      become: yes
      copy:
        src: dh1024.pem
        dest: "{{ openvpn_keys_directory }}/dh1024.pem"
        owner: nobody
        mode: 0400

    - name: Ensure server key is present
      become: yes
      copy:
        src: server.key
        dest: "{{ openvpn_keys_directory }}/server.key"
        owner: nobody
        mode: 0400

    - name: Ensure ta key is present
      become: yes
      copy:
        src: ta.key
        dest: "{{ openvpn_keys_directory }}/ta.key"
        owner: nobody
        mode: 0400

    - name: Ensure server certificate is present
      become: yes
      copy:
        src: server.crt
        dest: "{{ openvpn_keys_directory }}/server.crt"
        owner: nobody
        mode: 0444

    - name: Ensure CA certificate is present
      become: yes
      copy:
        src: ca.crt
        dest: "{{ openvpn_keys_directory }}/ca.crt"
        owner: nobody
        mode: 0444

    - name: Ensure configuration file is in-place
      become: yes
      template:
        src: server.conf.j2
        dest: "{{ openvpn_config_directory }}/openvpn.conf"

    # - name: Ensure OpenVPN is enabled in sysrc
    #   become: yes
    #   command: sysrc openvpn_enable="YES"

    # - name: Ensure OpenVPN interface is set to 'tun' in sysrc
    #   become: yes
    #   command: sysrc openvpn_if="tun"

    - name: Ensure IP routing is configured
      become: yes
      lineinfile:
        dest: /etc/rc.conf
        line: "{{ item }}"
      with_items:
        - openvpn_enable="YES"
        - openvpn_if="tun"
        - firewall_enable="YES"
        - firewall_type="open"
        - gateway_enable="YES"
        - natd_enable="YES"
        - natd_interface="hn0"
        - natd_flags="-dynamic -m"
        - "# test 14"
      notify: Reboot server

  handlers:
    - name: Reboot server
      become: yes
      shell: sleep 5 && reboot
      async: 1
      poll: 0
      ignore_errors: true
      changed_when: true
      notify: Wait for the server to reboot
    
    - name: Wait for the server to reboot
      local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        state: started
