---
- hosts: terra03vm

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Ensure terrabsd has password set
      become: yes
      user:
        name: terrabsd
        password: "{{ lookup('password', './tmp/passwordfile length=63 encrypt=md5_crypt') }}"

  tasks:
#    - name: Check pkg -N
#      command: pkg -N
#      register: pkg_bootstrapped_check
#      changed_when: false

    - name: Ensure pkg is bootstrapped
      become: yes
      command: pkg bootstrap
      environment:
        ASSUME_ALWAYS_YES: YES
#      when: pkg_bootstrapped_check.rc == 1

    - name: Ensure pkg is updated
      become: yes
      command: pkg update
      environment:
        ASSUME_ALWAYS_YES: YES
      changed_when: false

    - name: Ensure openvpn is installed
      become: yes
      pkgng:
        name: openvpn
        state: present

    - name: Ensure directory for keys exists
      become: yes
      file:
        dest: /usr/local/etc/openvpn/keys
        state: directory
        owner: nobody
        group: wheel
        mode: 0700

    - name: Ensure DH is present
      become: yes
      copy:
        src: dh1024.pem
        dest: /usr/local/etc/openvpn/keys/dh1024.pem
        owner: nobody
        mode: 0400

    - name: Ensure server key is present
      become: yes
      copy:
        src: server.key
        dest: /usr/local/etc/openvpn/keys/server.key
        owner: nobody
        mode: 0400

    - name: Ensure ta key is present
      become: yes
      copy:
        src: ta.key
        dest: /usr/local/etc/openvpn/keys/ta.key
        owner: nobody
        mode: 0400

    - name: Ensure server certificate is present
      become: yes
      copy:
        src: server.crt
        dest: /usr/local/etc/openvpn/keys/server.crt
        owner: nobody
        mode: 0444

    - name: Ensure CA certificate is present
      become: yes
      copy:
        src: ca.crt
        dest: /usr/local/etc/openvpn/keys/ca.crt
        owner: nobody
        mode: 0444

    - name: Ensure configuration file is in-place
      become: yes
      template:
        src: server.conf.j2
        dest: /usr/local/etc/openvpn/openvpn.conf

    - name: Ensure pkg is updated
      become: yes
      command: sysrc openvpn_enable="YES"

    - name: Ensure pkg is updated
      become: yes
      command: sysrc openvpn_if="tun"

    - name: Ensure pkg is updated
      become: yes
      command: service openvpn start

    - name: Ensure routing is configured
      become: yes
      lineinfile:
        dest: /etc/rc.conf
        line: "{{ item }}"
      with_items:
        - firewall_enable="YES"
        - firewall_type="open"
        - gateway_enable="YES"
        - natd_enable="YES"
        - natd_interface="hn0"
        - natd_flags="-dynamic -m"

    - name: Reboot
      become: yes
      command: reboot
